# This file was mostly copied from the following URL:
# https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
# MIT License
#
# Copyright (c) 2020 GitHub

name: Deploy Docs

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Jekyll
        run: |
          gem install jekyll jekyll-redirect-from bundler

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Sphinx
        run: |
          pip install sphinx==1.8 numpy
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        working-directory: ./docs
        run: jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          SKIP_SCALADOC: 0
          PRODUCTION: 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
